# Generated by Django 2.0 on 2018-01-28 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0015_auto_20180119_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.CharField(max_length=20, unique=True)),
                ('character_class', models.CharField(max_length=16)),
                ('light', models.IntegerField()),
                ('level', models.IntegerField()),
                ('race', models.CharField(max_length=16)),
                ('gender', models.CharField(max_length=1)),
                ('emblem_path', models.URLField()),
                ('date_last_played', models.DateTimeField()),
                ('minutes_played_total', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together={('member', 'character_id')},
        ),
    ]
