# Generated by Django 2.0 on 2018-01-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='minutes_played_total',
            new_name='minutes_played',
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(max_length=6),
        ),
    ]
