# Generated by Django 2.0 on 2018-01-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20180128_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='emblem_path',
            field=models.CharField(max_length=200),
        ),
    ]
