# Generated by Django 2.0 on 2018-01-31 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0017_member_date_last_played'),
    ]

    operations = [
        migrations.CreateModel(
            name='PvpStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('time_played', models.CharField(max_length=20)),
                ('kd_pga', models.FloatField()),
                ('best_weapon', models.CharField(max_length=20)),
                ('longest_spree', models.IntegerField()),
                ('most_kills', models.IntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member', unique=True)),
            ],
        ),
    ]
