# Generated by Django 2.0 on 2018-01-31 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pvpstats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvpstats',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
    ]
