# Generated by Django 2.0 on 2018-01-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvpstats', '0002_auto_20180130_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pvpstats',
            options={'verbose_name_plural': 'PvP Stats'},
        ),
        migrations.RenameField(
            model_name='pvpstats',
            old_name='best_weapon',
            new_name='favorite_weapon',
        ),
        migrations.RenameField(
            model_name='pvpstats',
            old_name='kd_pga',
            new_name='kd',
        ),
        migrations.RemoveField(
            model_name='pvpstats',
            name='time_played',
        ),
        migrations.AddField(
            model_name='pvpstats',
            name='seconds_played',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
