# Generated by Django 2.0 on 2018-02-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvpstats', '0004_auto_20180131_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvpstats',
            name='kd',
            field=models.FloatField(),
        ),
    ]
