# Generated by Django 2.0 on 2018-02-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvpstats', '0005_auto_20180131_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvpstats',
            name='number_matches',
            field=models.IntegerField(),
        ),
    ]
