# Generated by Django 2.0 on 2018-02-02 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pvpstats', '0007_auto_20180201_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pvpstats',
            old_name='longest_kill_distance',
            new_name='longest_kill',
        ),
    ]
