# Generated by Django 2.0 on 2018-02-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvpstats', '0008_auto_20180201_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvpstats',
            name='greatness',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
