# Generated by Django 2.0 on 2018-02-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvpstats', '0009_pvpstats_greatness'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvpstats',
            name='trials_kd',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pvpstats',
            name='trials_number_matches',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pvpstats',
            name='trials_win_loss_ratio',
            field=models.FloatField(null=True),
        ),
    ]
