# Generated by Django 2.0 on 2018-02-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvpstats', '0010_auto_20180205_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pvpstats',
            name='suicides',
        ),
        migrations.AddField(
            model_name='pvpstats',
            name='suicide_rate',
            field=models.FloatField(null=True),
        ),
    ]
