# Generated by Django 2.0 on 2018-02-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pvpstats', '0011_auto_20180207_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pvpstats',
            old_name='deaths_per_match',
            new_name='deaths_pga',
        ),
        migrations.RenameField(
            model_name='pvpstats',
            old_name='kills_per_match',
            new_name='kills_pga',
        ),
        migrations.RenameField(
            model_name='pvpstats',
            old_name='suicide_rate',
            new_name='suicides_pga',
        ),
    ]
