# Generated by Django 2.0 on 2017-12-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('creation_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('motto', models.CharField(max_length=200)),
                ('num_members', models.IntegerField()),
                ('founder', models.CharField(max_length=16)),
            ],
        ),
    ]
