# Generated by Django 2.0 on 2017-12-21 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0004_clan_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=16)),
                ('date_joined', models.CharField(max_length=100)),
                ('platform', models.IntegerField()),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clans.Clan')),
            ],
        ),
    ]
