# Generated by Django 2.0 on 2017-12-21 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0005_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='clan',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
