# Generated by Django 2.0 on 2017-12-21 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='platform',
            new_name='membership_type',
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('member_id', 'membership_type')},
        ),
    ]
