# Generated by Django 2.0 on 2017-12-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20171221_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='has_played_d2',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
