# Generated by Django 2.0 on 2017-12-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20171222_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='has_played_d2',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
