# Generated by Django 2.0 on 2017-12-22 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20171222_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='has_played_d2',
        ),
    ]
