# Generated by Django 2.0 on 2017-12-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_remove_member_has_played_d2'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='has_played_d2',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
