# Generated by Django 2.0 on 2017-12-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_member_has_played_d2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='has_played_d2',
            field=models.BooleanField(default=False),
        ),
    ]
