# Generated by Django 2.0 on 2017-12-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20171223_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
