# Generated by Django 2.0 on 2018-01-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auto_20180129_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date_last_played',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
