# Generated by Django 2.0 on 2018-02-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvestats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvestats',
            name='adventures',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pvestats',
            name='average_life',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pvestats',
            name='deaths_pga',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pvestats',
            name='heroic_public_events',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pvestats',
            name='kills_pga',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pvestats',
            name='longest_kill',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pvestats',
            name='longest_single_life',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pvestats',
            name='orbs_dropped_pga',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pvestats',
            name='orbs_gathered_pga',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pvestats',
            name='precision_kills_pga',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pvestats',
            name='resurrections_performed_pga',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pvestats',
            name='resurrections_received_pga',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pvestats',
            name='suicides',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pvestats',
            name='suicides_pga',
            field=models.FloatField(null=True),
        ),
    ]
