# Generated by Django 2.0 on 2018-02-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvestats', '0003_auto_20180208_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pvestats',
            name='activities_cleared',
        ),
        migrations.RemoveField(
            model_name='pvestats',
            name='adventures',
        ),
        migrations.RemoveField(
            model_name='pvestats',
            name='heroic_public_events',
        ),
        migrations.RemoveField(
            model_name='pvestats',
            name='number_activities',
        ),
        migrations.AddField(
            model_name='pvestats',
            name='number_nightfalls',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pvestats',
            name='number_prestige_nightfalls',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pvestats',
            name='number_story_missions',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pvestats',
            name='number_strikes',
            field=models.IntegerField(null=True),
        ),
    ]
