# Generated by Django 2.0 on 2018-02-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvestats', '0004_auto_20180210_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvestats',
            name='number_raid_clears',
            field=models.IntegerField(null=True),
        ),
    ]
