# Generated by Django 2.0 on 2018-02-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvestats', '0005_pvestats_number_raid_clears'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvestats',
            name='assists_pga',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pvestats',
            name='greatness',
            field=models.FloatField(null=True),
        ),
    ]
